query($term:String){
  recipes(filters:{ name:{contains:$term}}){
    data{
      id
      attributes {
        name
        likes
        description
        duration
        category {
          data{
            id
            attributes {
              name
              slug
            }
          }
        }
      }
    }
  }
}
