query($id:ID!){
  recipes(filters:{ autor:{id:{eq:$id}}}){
    data{
      id
      attributes {
        name
        likes
        description
        duration
        servings
        img
        category {
          data{
            id
            attributes {
              name
              slug
            }
          }
        }
      }
    }
  }
}
